# Rust workspace tasks.

# Lint
# | task            | type      | cwd |
# | --------------- | --------- | --- |
# | lint            | composite |     |
# | lint-fix        | composite |     |
# | lint-rust       | command   |     |
# | lint-fix-rust   | extend    |     |
# | lint-vstyle     | command   |     |
# | lint-fix-vstyle | command   |     |

[tasks.lint]
workspace = false
dependencies = [
	"lint-rust",
	"lint-vstyle",
]

[tasks.lint-fix]
workspace = false
dependencies = [
	"lint-fix-rust",
	"lint-fix-vstyle",
]

[tasks.lint-rust]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--workspace",
	"--all-targets",
	"--all-features",
	"--",
	"-D",
	"warnings",
]

[tasks.lint-fix-rust]
extend = "lint-rust"
args = [
	"clippy",
	"--fix",
	"--allow-dirty",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.lint-vstyle]
workspace = false
command = "cargo"
args = [
	"run",
	"--",
	"curate",
	"--workspace",
]

[tasks.lint-fix-vstyle]
workspace = false
command = "cargo"
args = [
	"run",
	"--",
	"tune",
	"--workspace",
	"--strict",
]


# Test
# | task      | type      | cwd |
# | --------- | --------- | --- |
# | test      | composite |     |
# | test-rust | command   |     |

[tasks.test]
workspace = false
dependencies = [
	"test-rust",
]

[tasks.test-rust]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
]


# Format
# | task           | type      | cwd |
# | -------------- | --------- | --- |
# | fmt            | composite |     |
# | fmt-check      | composite |     |
# | fmt-rust       | command   |     |
# | fmt-rust-check | extend    |     |
# | fmt-toml       | command   |     |
# | fmt-toml-check | extend    |     |

[tasks.fmt]
workspace = false
dependencies = [
	"fmt-rust",
	"fmt-toml",
]

[tasks.fmt-check]
workspace = false
dependencies = [
	"fmt-rust-check",
	"fmt-toml-check",
]

[tasks.fmt-rust]
workspace = false
script = "cargo +nightly fmt --all"

[tasks.fmt-rust-check]
extend = "fmt-rust"
script = "cargo +nightly fmt --all -- --check"

[tasks.fmt-toml]
workspace = false
command = "taplo"
args = [
	"fmt",
]

[tasks.fmt-toml-check]
extend = "fmt-toml"
args = [
	"fmt",
	"--check",
]


# Meta
# | task   | type      | cwd |
# | ------ | --------- | --- |
# | checks | composite |     |

[tasks.checks]
workspace = false
dependencies = [
	"fmt-check",
	"lint",
	"test",
]
