# Rust workspace tasks.

# Check
# | task         | type      | cwd |
# | ------------ | --------- | --- |
# | check        | composite |     |
# | check-rust   | command   |     |
# | check-vstyle | command   |     |

[tasks.check]
clear = true
workspace = false
dependencies = [
	"fmt-check",
	"check-rust",
	"check-vstyle",
	"test",
]

[tasks.check-rust]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--all-features",
	"--all-targets",
	"--workspace",
	"--",
	"-D",
	"clippy::all",
	"-D",
	"clippy::too_many_lines",
	"-D",
	"clippy::unwrap_used",
	"-D",
	"clippy::use_self",
	"-D",
	"clippy::wildcard_imports",
	"-D",
	"missing-docs",
	"-D",
	"unused-crate-dependencies",
	"-D",
	"warnings",
]

[tasks.check-vstyle]
workspace = false
command = "cargo"
args = [
	"vstyle",
	"curate",
	"--language",
	"rust",
	"--workspace",
	"--all-features"
]

# Format
# | task           | type      | cwd |
# | -------------- | --------- | --- |
# | fmt            | composite |     |
# | fmt-check      | composite |     |
# | fmt-rust       | command   |     |
# | fmt-rust-check | extend    |     |
# | fmt-toml       | command   |     |
# | fmt-toml-check | extend    |     |

[tasks.fmt]
workspace = false
dependencies = [
	"fmt-rust",
	"fmt-toml",
]

[tasks.fmt-check]
workspace = false
dependencies = [
	"fmt-rust-check",
	"fmt-toml-check",
]

[tasks.fmt-rust]
workspace = false
script = "cargo +nightly fmt --all"

[tasks.fmt-rust-check]
extend = "fmt-rust"
script = "cargo +nightly fmt --all -- --check"

[tasks.fmt-toml]
workspace = false
command = "taplo"
args = [
	"fmt",
]

[tasks.fmt-toml-check]
extend = "fmt-toml"
args = [
	"fmt",
	"--check",
]

# Lint
# | task        | type      | cwd |
# | ----------- | --------- | --- |
# | lint        | composite |     |
# | lint-rust   | command   |     |
# | lint-vstyle | command   |     |

[tasks.lint]
workspace = false
dependencies = [
	"lint-rust",
	"lint-vstyle",
]

[tasks.lint-rust]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--fix",
	"--allow-dirty",
	"--all-features",
	"--all-targets",
	"--workspace",
	"--",
	"-D",
	"clippy::all",
	"-D",
	"clippy::too_many_lines",
	"-D",
	"clippy::unwrap_used",
	"-D",
	"clippy::use_self",
	"-D",
	"clippy::wildcard_imports",
	"-D",
	"missing-docs",
	"-D",
	"unused-crate-dependencies",
	"-D",
	"warnings",
]

[tasks.lint-vstyle]
workspace = false
command = "cargo"
args = [
	"vstyle",
	"tune",
	"--language",
	"rust",
	"--workspace",
	"--all-features",
	"--strict",
]

# Test
# | task      | type      | cwd |
# | --------- | --------- | --- |
# | test      | composite |     |
# | test-rust | command   |     |

[tasks.test]
clear = true
workspace = false
dependencies = [
	"test-rust",
]

[tasks.test-rust]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
]

# Meta
# | task                  | type    | cwd |
# | --------------------- | ------- | --- |
# | bench-release-vstyle  | command |     |
# | bench-semantic-vstyle | command |     |

[tasks.bench-release-vstyle]
workspace = false
command = "bash"
args = [
	"scripts/bench-release-vstyle.sh",
]

[tasks.bench-semantic-vstyle]
workspace = false
command = "bash"
args = [
	"scripts/bench-semantic-vstyle.sh",
]
