name: Language Checks

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docs/**'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  rust-check:
    name: Rust check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache: true
          rustflags: ''
          components: rustfmt, clippy

      - name: Install nightly rustfmt
        run: rustup toolchain install nightly --component rustfmt

      - name: Install cargo-make
        uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: cargo-make

      - name: Install nextest
        uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: nextest

      - name: Run Rust format check
        run: cargo make fmt-rust-check

      - name: Run Rust style check
        uses: ./
        with:
          language: rust
          workspace: true
          args: --all-features
          version: checkout

      - name: Run Rust clippy
        run: cargo make check-rust

      - name: Run tests
        run: cargo make test-rust

  toml-check:
    name: TOML check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
        with:
          cache: true
          rustflags: ''

      - name: Install cargo-make
        uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: cargo-make

      - name: Install taplo
        uses: taiki-e/install-action@bffeee26d4db9be238a4ea78d8826604ebcb594d # v2.82.5
        with:
          tool: taplo

      - name: Run TOML format check
        run: cargo make fmt-toml-check
