name: Language Checks

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docs/**'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  rust-check:
    name: Rust check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          cache: true
          rustflags: ''
          components: rustfmt, clippy

      - name: Install nightly rustfmt
        run: rustup toolchain install nightly --component rustfmt

      - name: Install cargo-make
        uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
        with:
          tool: cargo-make

      - name: Install nextest
        uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
        with:
          tool: nextest

      - name: Run Rust format check
        run: cargo make fmt-rust-check

      - name: Run Rust style check
        uses: ./
        with:
          language: rust
          workspace: true
          args: --all-features
          version: checkout

      - name: Run Rust clippy
        run: cargo make check-rust

      - name: Run tests
        run: cargo make test-rust

  toml-check:
    name: TOML check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          cache: true
          rustflags: ''

      - name: Install cargo-make
        uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
        with:
          tool: cargo-make

      - name: Install taplo
        uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
        with:
          tool: taplo

      - name: Run TOML format check
        run: cargo make fmt-toml-check
